#!/usr/bin/env bash
# Idempotent dev-environment bootstrap for Cloud Agents.
#
# This is NOT the production installer (that is ../install.sh, which
# creates the lxcmgr service user, systemd unit and fail2ban jail and
# must run as root inside the target LXC). This script only prepares a
# local, runnable copy of the panel for development: a virtualenv, the
# Python dependencies (app + tests) and a placeholder .env so the app
# boots without a real Proxmox cluster.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# python3-venv is not guaranteed on the base image.
if ! python3 -c "import ensurepip" >/dev/null 2>&1; then
  PY_MM="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  sudo apt-get update -qq
  sudo apt-get install -y -qq "python${PY_MM}-venv" python3-pip
fi

if [ ! -x .venv/bin/python ]; then
  python3 -m venv .venv
fi

.venv/bin/pip install -q --upgrade pip
.venv/bin/pip install -q -r requirements.txt -r tests/requirements.txt

# Placeholder .env so the app can boot in the sandbox. No real Proxmox
# cluster is reachable here, so scheduler discovery is disabled. Real
# values belong in Cloud Agent secrets, not in the repo.
if [ ! -f .env ]; then
  cat > .env <<EOF
# Dev/sandbox .env (gitignored) generated by .cursor/install.sh.
LXCMGR_PVE_API_URL=https://127.0.0.1:8006
LXCMGR_PVE_TOKEN_ID=lxc-manager@pve!api
LXCMGR_PVE_TOKEN_SECRET=dev-placeholder-secret
LXCMGR_PVE_VERIFY_SSL=0

LXCMGR_DB_PATH=${REPO_DIR}/lxc-manager.db

LXCMGR_SESSION_SECRET=$(openssl rand -hex 32)

LXCMGR_ADMIN_USER=admin
LXCMGR_ADMIN_PASSWORD=devpassword123

LXCMGR_API_TOKEN=$(openssl rand -hex 32)

# No real Proxmox in the sandbox: skip the scheduler's synchronous
# startup discovery (it would try to reach the Proxmox API and fail).
LXCMGR_SKIP_SCHEDULER=1
LXCMGR_SELF_UPDATE=0
EOF
  echo ".cursor/install.sh: wrote placeholder .env"
fi

echo ".cursor/install.sh: dev environment ready"
