import sqlite3
from contextlib import contextmanager

from . import config

SCHEMA = """
CREATE TABLE IF NOT EXISTS guests (
    vmid INTEGER PRIMARY KEY,
    node TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,          -- lxc | qemu
    app_type TEXT NOT NULL,
    tags TEXT NOT NULL,
    maxmem INTEGER NOT NULL DEFAULT 0,   -- bytes, assigned
    maxcpu INTEGER NOT NULL DEFAULT 0,   -- cores, assigned
    ip TEXT NOT NULL DEFAULT '',
    os_family TEXT NOT NULL DEFAULT 'unknown',  -- linux | windows | other | unknown
    os_id TEXT NOT NULL DEFAULT 'unknown',      -- debian | ubuntu | windows | …
    update_supported INTEGER NOT NULL DEFAULT 0,  -- 1 = safe to run package updates
    last_seen TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
    vmid INTEGER PRIMARY KEY,
    cron TEXT NOT NULL,          -- standard 5-field cron
    enabled INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (vmid) REFERENCES guests(vmid)
);

CREATE TABLE IF NOT EXISTS runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vmid INTEGER NOT NULL,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    status TEXT NOT NULL,        -- running | ok | failed
    summary TEXT,
    detail TEXT,
    FOREIGN KEY (vmid) REFERENCES guests(vmid)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- security module: always cached, never fetched on every visit to the
-- guest page (unlike the kernel, which is live). Filled in on "Check
-- now" or the scheduler's weekly sweep.
CREATE TABLE IF NOT EXISTS security_checks (
    vmid INTEGER PRIMARY KEY,
    checked_at TEXT NOT NULL,
    ssh_active TEXT,
    password_auth TEXT,
    permit_root_login TEXT,
    authorized_keys_files INTEGER,
    fail2ban TEXT,
    sudo_nopasswd_lines INTEGER,
    listening_ports TEXT,
    raw TEXT,
    FOREIGN KEY (vmid) REFERENCES guests(vmid)
);

-- backups module: one Proxmox API call per PBS storage (no SSH),
-- refreshed hourly by the scheduler, plus "Back up now" on demand.
-- PK is (vmid, storage) so each PBS backend gets its own row; a new
-- storage discovered at sync time just inserts more rows. last_backup_at
-- NULL means no backup was ever found for this guest on that storage.
CREATE TABLE IF NOT EXISTS backup_status (
    vmid INTEGER NOT NULL,
    storage TEXT NOT NULL,
    checked_at TEXT NOT NULL,
    last_backup_at TEXT,
    last_backup_size INTEGER,
    verification TEXT,
    PRIMARY KEY (vmid, storage),
    FOREIGN KEY (vmid) REFERENCES guests(vmid)
);

-- On-demand "Back up now" history (same shape as update `runs`).
-- Scheduled PBS jobs outside this app are not recorded here.
CREATE TABLE IF NOT EXISTS backup_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vmid INTEGER NOT NULL,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    status TEXT NOT NULL,        -- running | ok | failed
    summary TEXT,
    detail TEXT,
    FOREIGN KEY (vmid) REFERENCES guests(vmid)
);

-- Machines running homelab-client. id is generated by the client
-- (stable across reinstalls if the client keeps its id file).
CREATE TABLE IF NOT EXISTS clients (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    hostname TEXT NOT NULL DEFAULT '',
    platform TEXT NOT NULL DEFAULT 'linux',  -- ubuntu | raspbian | proxmox | synology | unraid | debian | other
    os_id TEXT NOT NULL DEFAULT '',
    os_version TEXT NOT NULL DEFAULT '',
    ip TEXT NOT NULL DEFAULT '',
    capabilities TEXT NOT NULL DEFAULT '[]', -- json list: apt, docker, lxc, qemu, …
    cpu_percent REAL,
    mem_used INTEGER,
    mem_total INTEGER,
    temp_c REAL,
    uptime_seconds INTEGER,
    loadavg TEXT NOT NULL DEFAULT '',
    version TEXT NOT NULL DEFAULT '',
    last_seen TEXT,
    last_status TEXT NOT NULL DEFAULT 'unknown', -- online | offline
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS client_resources (
    client_id TEXT NOT NULL,
    kind TEXT NOT NULL,          -- docker | lxc | qemu
    resource_id TEXT NOT NULL,   -- container name or vmid
    name TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT '',
    extra TEXT NOT NULL DEFAULT '', -- json
    PRIMARY KEY (client_id, kind, resource_id),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- Jobs the manager enqueues; clients poll and report back.
CREATE TABLE IF NOT EXISTS client_jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id TEXT NOT NULL,
    kind TEXT NOT NULL,          -- sys-update | docker-update | lxc-update | qemu-update | self-update
    target TEXT NOT NULL DEFAULT '', -- empty = whole host; else container/vmid
    status TEXT NOT NULL,        -- queued | running | ok | failed
    created_at TEXT NOT NULL,
    started_at TEXT,
    finished_at TEXT,
    summary TEXT,
    detail TEXT,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- Runtime settings (Telegram, notify toggles). Env is the bootstrap
-- default; this table wins once a value is saved from the UI.
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""


@contextmanager
def get_conn():
    conn = sqlite3.connect(config.DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


MIGRATIONS = [
    "ALTER TABLE guests ADD COLUMN maxmem INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE guests ADD COLUMN maxcpu INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE guests ADD COLUMN ip TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE guests ADD COLUMN os_family TEXT NOT NULL DEFAULT 'unknown'",
    "ALTER TABLE guests ADD COLUMN os_id TEXT NOT NULL DEFAULT 'unknown'",
    "ALTER TABLE guests ADD COLUMN update_supported INTEGER NOT NULL DEFAULT 0",
]


def _migrate_backup_status_per_storage(conn: sqlite3.Connection) -> None:
    """Old schema had vmid as the sole PK (one row = one guest on the
    single hard-coded unraid-pbs). Rebuild with (vmid, storage) and
    attribute existing rows to PBS_STORAGE so nothing is lost on upgrade."""
    cols = {r[1] for r in conn.execute("PRAGMA table_info(backup_status)").fetchall()}
    if not cols:
        return  # CREATE TABLE in SCHEMA just made the new shape
    if "storage" in cols:
        return
    conn.execute(
        """CREATE TABLE backup_status_new (
               vmid INTEGER NOT NULL,
               storage TEXT NOT NULL,
               checked_at TEXT NOT NULL,
               last_backup_at TEXT,
               last_backup_size INTEGER,
               verification TEXT,
               PRIMARY KEY (vmid, storage),
               FOREIGN KEY (vmid) REFERENCES guests(vmid)
           )"""
    )
    conn.execute(
        """INSERT INTO backup_status_new
             (vmid, storage, checked_at, last_backup_at, last_backup_size, verification)
           SELECT vmid, ?, checked_at, last_backup_at, last_backup_size, verification
           FROM backup_status""",
        (config.PBS_STORAGE,),
    )
    conn.execute("DROP TABLE backup_status")
    conn.execute("ALTER TABLE backup_status_new RENAME TO backup_status")


def get_setting(key: str, default: str = "") -> str:
    with get_conn() as conn:
        row = conn.execute("SELECT value FROM settings WHERE key=?", (key,)).fetchone()
    if row is None:
        return default
    return row["value"]


def set_setting(key: str, value: str) -> None:
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
            (key, value),
        )


def init_db():
    with get_conn() as conn:
        conn.executescript(SCHEMA)
        for stmt in MIGRATIONS:
            try:
                conn.execute(stmt)
            except sqlite3.OperationalError as exc:
                if "duplicate column" not in str(exc):
                    raise
        _migrate_backup_status_per_storage(conn)
