"""All user-facing UI text, kept out of the templates and route code so
copy can change without touching logic. Registered as a Jinja global
(see templates.py) — every template reads it as `t.xxx`."""

t = {
    "app_name": "homelab-manager",
    "nav_dashboard": "Dashboard",
    "nav_guests": "Guests",
    "nav_settings": "Settings",
    "nav_logout": "Log out",
    "back": "← back",

    # dashboard
    "index_subtitle": "Homelab clients. Online = heartbeat within the last 90s.",
    "refresh": "Refresh",
    "refreshing": "refreshing…",
    "clients_online": "online",
    "clients_offline": "offline",
    "no_clients_yet": "No clients yet. Install homelab-client on a machine and paste the cluster key from Settings.",
    "col_client": "Client",
    "col_platform": "Platform",
    "col_status": "Status",
    "col_cpu": "CPU",
    "col_ram": "RAM",
    "col_temp": "Temp",
    "col_seen": "Last seen",
    "status_online": "online",
    "status_offline": "offline",
    "job_queued": "Queued — the client will pick it up on the next heartbeat.",
    "unknown_job": "Unknown job type.",
    "update_host": "Update host",
    "update_docker": "Update containers",
    "update_self": "Update client",
    "section_docker": "Docker",
    "section_lxc": "LXC",
    "section_vms": "VMs",
    "section_jobs": "Jobs",
    "no_docker": "No containers reported.",
    "no_lxc": "No LXC reported.",
    "no_vms": "No VMs reported.",
    "no_jobs_yet": "No jobs yet.",
    "col_resource": "Name",
    "col_kind": "Kind",
    "capabilities": "Capabilities",
    "uptime": "Uptime",
    "load": "Load",
    "version_label": "Client",
    "kernel_label": "OS",
    "guests_heading": "Proxmox guests",
    "guests_subtitle": "Guests tagged 'managed' (Proxmox API). Weekly updates need 'auto-update' too.",

    # guests table (legacy lxc-manager)
    "col_vmid": "VMID",
    "col_name": "Name",
    "col_host": "Host",
    "col_app": "App",
    "col_update": "Update",
    "col_security": "Security",
    "col_backups": "Backups",

    # status badges (update)
    "status_ok": "OK",
    "status_failed": "FAILED",
    "status_warning": "WARNING",
    "status_running": "…",
    "status_never": "—",

    # status badges (security)
    "security_ok": "OK",
    "security_warning": "⚠",
    "security_never": "—",
    "security_warning_tooltip": "One or more checks failed — see the guest page",
    "backups_warning_tooltip": "Some storages are OK, others are not — see the guest page",
    "backups_failed_tooltip": "No healthy backup on any storage — see the guest page",

    # guest page
    "vcpu": "vCPU",
    "ram": "RAM",
    "kernel_host": "host kernel",
    "kernel": "kernel",
    "loading": "loading…",
    "section_security": "Security",
    "section_update": "Update",
    "section_backups": "Backups",
    "section_schedule": "Schedule",
    "section_history": "History",
    "guest_type_lxc": "LXC",
    "guest_type_vm": "VM",
    "label_type": "Type",
    "label_os": "OS",
    "label_os_family": "Family",
    "label_os_updates": "OS updates",
    "label_update_via": "Update via",
    "os_updates_apt": "apt",
    "os_updates_disabled_windows": "disabled (Windows)",
    "os_updates_disabled": "disabled",
    "update_via_agent": "Proxmox host agent",
    "col_type": "Type",
    "col_os": "OS",
    "check_last_backup": "Last backup",
    "check_verification": "Verification",
    "check_size": "Size",
    "backup_now": "Back up now",
    "backing_up": "Backing up…",
    "backup_started": "Started — backup + integrity verify; can take a while.",
    "no_backups_yet": "No backups found.",
    "no_backup_on_storage": "No backup on this storage.",
    "no_backup_runs_yet": "No on-demand backups yet.",
    "check_now": "Check now",
    "check_again": "Check again",
    "checking": "Checking…",
    "icon_check": "⟳",
    "icon_run": "▶",
    "not_checked_yet": "Not checked yet.",
    "last_checked": "last checked",
    "check_ssh": "SSH",
    "check_password": "password",
    "password_allowed": "allowed",
    "password_disabled": "disabled",
    "check_keys": "keys",
    "check_root_login": "root login",
    "check_fail2ban": "fail2ban",
    "check_sudo_nopasswd": "sudo without password",
    "check_ports": "ports",
    "run_now": "Run now",
    "run_launched": "Launched — check the history in a few seconds.",
    "last_run": "Last run",
    "next_scheduled": "Next scheduled",
    "cron_placeholder": "0 4 * * 6",
    "active_label": "active",
    "saved": "Saved.",
    "invalid_cron": "Invalid cron expression — not saved.",
    "no_runs_yet": "No runs yet.",
    "unknown": "?",

    # login
    "login_title": "Log in",
    "login_error": "Wrong username or password.",
    "login_rate_limited": "Too many failed logins. Try again in a few minutes.",
    "username": "Username",
    "password": "Password",
    "login_button": "Log in",

    # settings
    "settings_title": "Settings",
    "session_label": "Session",
    "change_password_title": "Change password",
    "current_password": "Current password",
    "new_password": "New password",
    "change_button": "Change",
    "wrong_current_password": "Current password is wrong.",
    "password_too_short": "New password must be at least 12 characters.",
    "password_too_long": "New password is too long.",
    "password_updated": "Password updated.",
    "section_cluster": "Cluster key",
    "cluster_help": "Created on first install. Paste the same key into every homelab-client.",
    "cluster_install_hint": "Client install",
    "section_telegram": "Telegram",
    "telegram_token": "Bot token",
    "telegram_chat_id": "Chat ID",
    "telegram_events": "Notify on",
    "notify_client_offline": "client offline",
    "notify_client_online": "client online",
    "notify_update_ok": "update ok",
    "notify_update_failed": "update failed",
    "notify_self_update": "self-update",
    "telegram_test": "Send test",
    "telegram_test_ok": "Test sent.",
    "telegram_test_failed": "Could not send — check token and chat ID.",
    "save_button": "Save",
    "section_self_update": "Self-update",
    "update_check": "Check",
    "update_apply": "Update now",
    "update_up_to_date": "Already up to date.",
    "update_behind": "{n} commit(s) behind origin.",
    "update_started": "Updating — the panel will restart in a moment.",
    "current_version": "Version",
    "current_revision": "Revision",
}
