"""All user-facing UI text, kept out of the templates and route code so
copy can change without touching logic. Registered as a Jinja global
(see templates.py) — every template reads it as `t.xxx`."""

t = {
    "app_name": "lxc-manager",
    "nav_settings": "Settings",
    "nav_logout": "Log out",
    "back": "← back",

    # index
    "index_subtitle": "Guests tagged 'auto-update', discovered via the Proxmox API.",
    "refresh": "Refresh",
    "refreshing": "refreshing…",
    "col_vmid": "VMID",
    "col_name": "Name",
    "col_host": "Host",
    "col_app": "App",
    "col_update": "Update",
    "col_security": "Security",
    "col_backups": "Backups",

    # status badges (update)
    "status_ok": "OK",
    "status_failed": "FAILED",
    "status_warning": "WARNING",
    "status_running": "…",
    "status_never": "—",

    # status badges (security)
    "security_ok": "OK",
    "security_warning": "⚠",
    "security_never": "—",
    "security_warning_tooltip": "One or more checks failed — see the guest page",
    "backups_warning_tooltip": "Some storages are OK, others are not — see the guest page",
    "backups_failed_tooltip": "No healthy backup on any storage — see the guest page",

    # guest page
    "vcpu": "vCPU",
    "ram": "RAM",
    "kernel_host": "host kernel",
    "kernel": "kernel",
    "loading": "loading…",
    "section_security": "Security",
    "section_update": "Update",
    "section_backups": "Backups",
    "section_schedule": "Schedule",
    "section_history": "History",
    "guest_type_lxc": "LXC",
    "guest_type_vm": "VM",
    "label_type": "Type",
    "label_os": "OS",
    "label_os_family": "Family",
    "label_os_updates": "OS updates",
    "label_update_via": "Update via",
    "os_updates_apt": "apt",
    "os_updates_disabled_windows": "disabled (Windows)",
    "os_updates_disabled": "disabled",
    "update_via_agent": "Proxmox host agent",
    "col_type": "Type",
    "col_os": "OS",
    "check_last_backup": "Last backup",
    "check_verification": "Verification",
    "check_size": "Size",
    "backup_now": "Back up now",
    "backing_up": "Backing up…",
    "backup_started": "Started — this can take a while for a large guest.",
    "no_backups_yet": "No backups found.",
    "no_backup_on_storage": "No backup on this storage.",
    "no_backup_runs_yet": "No on-demand backups yet.",
    "check_now": "Check now",
    "check_again": "Check again",
    "checking": "Checking…",
    "icon_check": "⟳",
    "icon_run": "▶",
    "not_checked_yet": "Not checked yet.",
    "last_checked": "last checked",
    "check_ssh": "SSH",
    "check_password": "password",
    "password_allowed": "allowed",
    "password_disabled": "disabled",
    "check_keys": "keys",
    "check_root_login": "root login",
    "check_fail2ban": "fail2ban",
    "check_sudo_nopasswd": "sudo without password",
    "check_ports": "ports",
    "run_now": "Run now",
    "run_launched": "Launched — check the history in a few seconds.",
    "last_run": "Last run",
    "next_scheduled": "Next scheduled",
    "cron_placeholder": "0 4 * * 6",
    "active_label": "active",
    "saved": "Saved.",
    "invalid_cron": "Invalid cron expression — not saved.",
    "no_runs_yet": "No runs yet.",
    "unknown": "?",

    # login
    "login_title": "Log in",
    "login_error": "Wrong username or password.",
    "login_rate_limited": "Too many failed logins. Try again in a few minutes.",
    "username": "Username",
    "password": "Password",
    "login_button": "Log in",

    # settings
    "settings_title": "Settings",
    "session_label": "Session",
    "change_password_title": "Change password",
    "current_password": "Current password",
    "new_password": "New password",
    "change_button": "Change",
    "wrong_current_password": "Current password is wrong.",
    "password_too_short": "New password must be at least 12 characters.",
    "password_too_long": "New password is too long.",
    "password_updated": "Password updated.",
}
